version: '3.8'
services: 
    backend:
        container_name: backend
        restart: always
        build: ./backend
        ports: 
            - "8080:8080"
        links: 
            - mongodb
        
    frontend:
        container_name: frontend
        restart: always
        build: ./frontend
        ports: 
            - "3000:3000"
        links: 
            - backend
        

    mongodb:
        image : mongo
        container_name: mongodb
        environment:
        - PUID=1000
        - PGID=1000
        volumes:
        - data:/data/db
        ports:
        - "27017:27017"
    
    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: example
        
volumes: 
    data:

# networks:
#     frontend:
#         external: true
#     sample:
#         external: true
# secrets:
#     password:
#         file: /backend/password.txt